### PR TITLE
Update and rename HNSW_Search.gsql to HNSW_Overlap_Search.gsql

### PR DESCRIPTION
**Pull request by RobRossmiller-TG**
[PR 214](https://github.com/tigergraph/CoPilot/pull/214/files) updated the query name in the code.

### CODE REVIEW

**Comment by billshitg** [comment]
Interesting. I updated it in that PR because it is already called "HNSW_Overlap_Search".

**Comment by parkererickson-tg** [comment]
HNSW search and Overlap search are two different things

**Review by parkererickson-tg — CHANGES_REQUESTED** [review]
Actually this whole directory should be deleted - the correct search queries are in `/supportai/retrievers`

**Comment by RobRossmiller-TG** [comment]
> Interesting. I updated it in that PR because it is already called "HNSW_Overlap_Search".

> HNSW search and Overlap search are two different things

Point of the PR is just to align what's in the repo with what's in the DB. Ensure that what name is in the code matches what's installed in the db and defined in the repo

**Pull request closed without merging**
